### PR TITLE
etcd certs check and renew

### LINKED ISSUE #17: Provide a procedure to renew certficates
Currently, the self generated CA certificate has 5 years of lifetime and other certificates have 1 year. Provide a procedure/script to renew certificates on a live setup without service disruption.

### PR DESCRIPTION
**Pull request by ptx96**
Closes #17

### CODE REVIEW

**Comment by ptx96** [comment]
This PR will stay in draft until kamaji server-side fixes will prevent us to remove the webhook;
you can still give it a try and LMK @bsctl

**Review by prometherion — CHANGES_REQUESTED** [review]
The implementation is wrong here.

There's no need to scale down Kamaji, removing webhooks and other breaking activities to perform a simple operation.

Although Kamaji is preventing Secret resources deletion used by a Datastore, the update is not blocked: with that said, an in-place certificate replacement can be issued, and restarting the `etcd` Statefulset by deleting the pods in a graceful way (or by scaling in and out and waiting for rollout).

**Comment by ptx96** [comment]
> The implementation is wrong here.
> 
> There's no need to scale down Kamaji, removing webhooks and other breaking activities to perform a simple operation.
> 
> Although Kamaji is preventing Secret resources deletion used by a Datastore, the update is not blocked: with that said, an in-place certificate replacement can be issued, and restarting the `etcd` Statefulset by deleting the pods in a graceful way (or by scaling in and out and waiting for rollout).

You are right, thanks for the suggestions!

Anyway, to patch secrets and restart the sts we need additional permission on the kamaji-etcd sa (added into the latest commit just to give an idea), OR to create new sa/role/rolebinding on the fly for the job execution.

Also, TCP pods are able to detect the configuration change, to give error on api-server container and self-heal themself, but I preferred to scale tcp to decrease downtime

**Review by bsctl — CHANGES_REQUESTED** [review]
@ptx96 need to document to upgrade the helm release before to run the renew otherwise the renew script fails because of missing RBAC (only if installed with previous chart releases).

**Review by bsctl — COMMENTED** [review]
@ptx96 do we need to change the chart release version since we're going to change the templates

**Review by bsctl — APPROVED** [review]
lgtm!

**Pull request merged**
